// Generated by scripts/minigpt-training-figures. Do not edit by hand.
//
//     scripts/minigpt-training-figures runs/minigpt-v1/metrics.jsonl 77000 \
//       > frontend/src/minigpt_training.rs
//
// MOUNT INSTRUCTION: add this one line to main.rs, inside the
// `Model::MiniGpt => view! { <section class="about-model" ...>` arm, in the
// same position `<TrainingProgress/>` occupies in the `Model::AlphaMini` arm:
//
//     <MiniGptTrainingProgress/>
//
// The module is declared in main.rs but not yet rendered, because the
// `Model::MiniGpt` arm does not exist in this tree yet. Drop the
// `allow(dead_code)` below once the component is mounted.


use leptos::prelude::*;

const TRAIN_LOSS_PTS: &str = "45.6,32.5 49.3,108.1 52.9,141.3 56.5,157.5 60.2,166.9 63.8,172.4 67.5,176.2 71.1,178.8 74.7,180.8 78.4,182.6 82,184.4 85.6,185.6 89.3,186.6 92.9,187.5 96.5,188.6 100.2,189.4 103.8,190.1 107.5,190.9 111.1,191.2 114.7,191.9 118.4,192.3 122,192.9 125.6,193.5 129.3,193.9 132.9,194.2 136.5,194.5 140.2,195 143.8,195.3 147.5,195.7 151.1,195.9 154.7,196.3 158.4,196.6 162,196.6 165.6,197.1 169.3,197.3 172.9,197.5 176.5,197.8 180.2,197.8 183.8,198.1 187.5,198.2 191.1,198.6 194.7,198.7 198.4,198.9 202,199 205.6,199.2 209.3,199.2 212.9,199.7 216.5,199.5 220.2,199.9 223.8,199.9 227.5,199.9 231.1,200.3 234.7,200.4 238.4,200.6 242,200.7 245.6,200.8 249.3,200.7 252.9,200.9 256.5,201.1 260.2,201.2 263.8,201.2 267.5,201.5 271.1,201.5 274.7,201.6 278.4,201.8 282,201.9 285.6,202.1 289.3,202 292.9,202.2 296.5,202.1 300.2,202.3 303.8,202.4 307.5,202.4 311.1,202.6 314.7,202.6 318.4,202.7 322,202.7 325.6,203.1 329.3,203.1 332.9,203.2 336.5,203.2 340.2,203.1 343.8,203.4 347.5,203.4 351.1,203.5 354.7,203.5 358.4,203.8 362,204 365.6,204.1 369.3,204.2 372.9,204.1 376.5,204.3 380.2,204.2 383.8,204.5 387.5,204.4 391.1,204.3 394.7,204.6 398.4,204.6 402,204.7 405.6,204.7 409.3,204.6 412.9,204.8 416.5,204.8 420.2,205 423.8,205 427.5,205 431.1,205.2 434.7,205.2 438.4,205.3 442,205.2 445.6,205.3 449.3,205.4 452.9,205.5 456.5,205.4 460.2,205.5 463.8,205.6 467.5,205.6 471.1,205.6 474.7,205.8 478.4,205.8 482,205.9 485.6,205.9 489.3,206 492.9,206.1 496.5,206 500.2,206 503.8,206.1 507.5,206.1 511.1,206.2 514.7,206.1 518.4,206.3 522,206.3 525.6,206.3 529.3,206.4 532.9,206.3 536.5,206.3 540.2,206.4 543.8,206.5 547.5,206.5 551.1,206.5 554.7,206.5 558.4,206.6 562,206.6 565.6,206.6 569.3,206.6 572.9,206.6 576.5,206.7 580.2,206.7 583.8,206.6 587.5,206.6 591.1,206.7 594.7,206.8 598.4,206.8 602,206.7";

const VAL_LOSS_PTS: &str = "45.6,75.4 49.3,126 52.9,150.3 56.5,162.7 60.2,170.4 63.8,174.9 67.5,177.8 71.1,180.5 74.7,182.1 78.4,184.3 82,185.8 85.6,187.3 89.3,188.4 92.9,189.1 96.5,190.2 100.2,190.2 103.8,191.5 107.5,192.2 111.1,192.8 114.7,193.3 118.4,193.9 122,194.4 125.6,194.8 129.3,195.2 132.9,195.3 136.5,196 140.2,196.4 143.8,196.6 147.5,196.9 151.1,197.4 154.7,197.5 158.4,197.8 162,198.1 165.6,198.3 169.3,198.6 172.9,198.6 176.5,199 180.2,198.9 183.8,199.4 187.5,199.5 191.1,199.7 194.7,200.1 198.4,200 202,200.3 205.6,200.6 209.3,200.7 212.9,200.9 216.5,201 220.2,201 223.8,201.2 227.5,201.4 231.1,201.5 234.7,201.5 238.4,201.7 242,201.9 245.6,202 249.3,202.2 252.9,202.3 256.5,202.4 260.2,202.6 263.8,202.6 267.5,202.7 271.1,202.8 274.7,203 278.4,202.9 282,203.1 285.6,203.1 289.3,203.3 292.9,203.4 296.5,203.6 300.2,203.7 303.8,203.7 307.5,203.9 311.1,203.8 314.7,203.8 318.4,204 322,204.2 325.6,204.2 329.3,204.3 332.9,204.4 336.5,204.5 340.2,204.5 343.8,204.6 347.5,204.6 351.1,204.8 354.7,204.9 358.4,204.8 362,205 365.6,205.2 369.3,205.2 372.9,205.3 376.5,205.3 380.2,205.3 383.8,205.5 387.5,205.5 391.1,205.6 394.7,205.6 398.4,205.7 402,205.8 405.6,205.8 409.3,205.9 412.9,206 416.5,206 420.2,206.1 423.8,206.1 427.5,206.1 431.1,206.3 434.7,206.4 438.4,206.4 442,206.5 445.6,206.6 449.3,206.5 452.9,206.6 456.5,206.7 460.2,206.7 463.8,206.8 467.5,206.8 471.1,206.8 474.7,206.9 478.4,206.9 482,207 485.6,207 489.3,207 492.9,207.1 496.5,207.1 500.2,207.2 503.8,207.2 507.5,207.3 511.1,207.3 514.7,207.3 518.4,207.4 522,207.5 525.6,207.5 529.3,207.5 532.9,207.5 536.5,207.5 540.2,207.6 543.8,207.6 547.5,207.6 551.1,207.7 554.7,207.7 558.4,207.7 562,207.7 565.6,207.7 569.3,207.8 572.9,207.8 576.5,207.8 580.2,207.8 583.8,207.8 587.5,207.9 591.1,207.9 594.7,207.9 598.4,207.9 602,208";

const TOP1_PTS: &str = "46.3,105.5 50.6,87.8 54.9,78.4 59.2,70.6 63.5,65.1 67.8,61.4 72.1,59.5 76.4,56.6 80.7,55.4 85,53.2 89.3,51.9 93.6,50.3 97.9,49 102.2,48.3 106.5,46.9 110.8,47 115.1,45.4 119.4,45 123.7,44.1 128,43.2 132.3,42.8 136.6,42.6 140.9,41.8 145.2,41.3 149.5,40.9 153.8,40.5 158.1,39.9 162.4,39.5 166.7,39.1 171,38.6 175.3,38.4 179.6,38.3 183.9,37.7 188.2,37.3 192.5,37 196.8,36.6 201.1,36.5 205.4,36.5 209.6,35.7 213.9,35.5 218.2,35.3 222.5,34.8 226.8,35 231.1,34.7 235.4,34.2 239.7,34 244,33.8 248.3,33.7 252.6,33.8 256.9,33.5 261.2,32.7 265.5,32.9 269.8,32.8 274.1,32.8 278.4,32.5 282.7,32.2 287,32.4 291.3,31.8 295.6,31.9 299.9,31.4 304.2,31.4 308.5,31.1 312.8,31.1 317.1,30.8 321.4,30.8 325.7,30.8 330,30.6 334.3,30.6 338.6,30.2 342.9,30 347.2,30.2 351.5,29.9 355.8,29.7 360.1,30 364.4,29.8 368.7,29.4 373,29.4 377.3,29.3 381.6,29.1 385.9,28.9 390.2,28.8 394.5,28.7 398.8,28.7 403.1,28.5 407.4,28.7 411.7,28.4 416,28.3 420.3,28.3 424.6,27.7 428.9,28 433.2,28 437.5,27.7 441.8,27.9 446.1,27.4 450.4,27.4 454.7,27.2 459,27.2 463.3,27.3 467.6,27.1 471.9,27.1 476.2,26.9 480.5,26.8 484.8,26.7 489.1,26.7 493.4,26.7 497.7,26.4 502,26.5 506.3,26.3 510.6,26.2 514.9,25.9 519.2,25.7 523.5,25.7 527.8,25.9 532.1,25.8 536.4,25.6 540.6,25.6 544.9,25.7 549.2,25.6 553.5,25.4 557.8,25.2 562.1,25.2 566.4,25.3 570.7,25.4 575,25.1 579.3,25 583.6,25.1 587.9,25.2 592.2,25 596.5,24.9 600.8,24.9 605.1,24.8 609.4,24.7 613.7,24.6 618,24.6 622.3,24.4 626.6,24.6 630.9,24.5 635.2,24.4 639.5,24.5 643.8,24.2 648.1,24.3 652.4,24.1 656.7,24.3 661,24.4 665.3,24.1 669.6,24.1 673.9,24.4 678.2,24.2 682.5,24.1 686.8,24 691.1,24 695.4,23.7 699.7,24 704,23.9";

const LR_PTS: &str = "46.3,88 50.6,53.9 54.9,19.9 59.2,17.2 63.5,17.2 67.8,17.3 72.1,17.4 76.4,17.4 80.7,17.6 85,17.7 89.3,17.8 93.6,18 97.9,18.2 102.2,18.4 106.5,18.6 110.8,18.9 115.1,19.2 119.4,19.5 123.7,19.8 128,20.1 132.3,20.4 136.6,20.8 140.9,21.2 145.2,21.6 149.5,22 153.8,22.5 158.1,22.9 162.4,23.4 166.7,23.9 171,24.4 175.3,24.9 179.6,25.5 183.9,26.1 188.2,26.6 192.5,27.2 196.8,27.8 201.1,28.5 205.4,29.1 209.6,29.8 213.9,30.5 218.2,31.1 222.5,31.8 226.8,32.6 231.1,33.3 235.4,34 239.7,34.8 244,35.6 248.3,36.4 252.6,37.2 256.9,38 261.2,38.8 265.5,39.6 269.8,40.5 274.1,41.3 278.4,42.2 282.7,43 287,43.9 291.3,44.8 295.6,45.7 299.9,46.6 304.2,47.5 308.5,48.4 312.8,49.4 317.1,50.3 321.4,51.2 325.7,52.2 330,53.1 334.3,54.1 338.6,55.1 342.9,56 347.2,57 351.5,58 355.8,58.9 360.1,59.9 364.4,60.9 368.7,61.9 373,62.8 377.3,63.8 381.6,64.8 385.9,65.8 390.2,66.8 394.5,67.8 398.8,68.7 403.1,69.7 407.4,70.7 411.7,71.7 416,72.6 420.3,73.6 424.6,74.5 428.9,75.5 433.2,76.5 437.5,77.4 441.8,78.3 446.1,79.3 450.4,80.2 454.7,81.1 459,82 463.3,82.9 467.6,83.8 471.9,84.7 476.2,85.6 480.5,86.5 484.8,87.3 489.1,88.2 493.4,89 497.7,89.9 502,90.7 506.3,91.5 510.6,92.3 514.9,93.1 519.2,93.9 523.5,94.6 527.8,95.4 532.1,96.1 536.4,96.8 540.6,97.5 544.9,98.2 549.2,98.9 553.5,99.5 557.8,100.2 562.1,100.8 566.4,101.4 570.7,102 575,102.6 579.3,103.2 583.6,103.7 587.9,104.3 592.2,104.8 596.5,105.3 600.8,105.8 605.1,106.2 609.4,106.7 613.7,107.1 618,107.5 622.3,107.9 626.6,108.2 630.9,108.6 635.2,108.9 639.5,109.2 643.8,109.5 648.1,109.8 652.4,110.1 656.7,110.3 661,110.5 665.3,110.7 669.6,110.9 673.9,111 678.2,111.2 682.5,111.3 686.8,111.4 691.1,111.4 695.4,111.5 699.7,111.5 704,111.5";

#[component]
pub fn MiniGptTrainingProgress() -> impl IntoView {
    view! {
        <div class="training">
            <div class="training-heading">
                <h3>"Training progress"</h3>
                <div class="training-intro">
                    <p>
                        "MiniGPT is trained once, on 11.2 million strong human games, to predict the move a strong player would make next. There is no self-play and no search: every point below is one pass of the optimizer over more of the same corpus. The run completed its full 77,000-step horizon."
                    </p>
                    <p>
                        "Loss measures how surprised the model is by the move that was actually played. Lower is better, and the validation curve is measured on games the optimizer never sees."
                    </p>
                </div>
            </div>

            <dl class="training-stats">
                <div>
                    <dt>"Training steps"</dt>
                    <dd class="stat-value">"77,000 / 77,000"</dd>
                    <dd class="stat-note">
                        "100.0% of the frozen horizon. One step is 256 whole games, about 20,000 real move tokens."
                    </dd>
                </div>
                <div>
                    <dt>"Train loss"</dt>
                    <dd class="stat-value">"5.78 → 1.45"</dd>
                    <dd class="stat-note">
                        "Loss on the batches the optimizer is updating on, one point per evaluation."
                    </dd>
                </div>
                <div>
                    <dt>"Validation loss"</dt>
                    <dd class="stat-value">"4.72 → 1.42"</dd>
                    <dd class="stat-note">
                        "The same loss on held-out games. Its best value, 1.42, came at step 77,000."
                    </dd>
                </div>
                <div>
                    <dt>"Move accuracy"</dt>
                    <dd class="stat-value">"53.4%"</dd>
                    <dd class="stat-note">
                        "How often the single highest-scoring legal move is the one the human actually played, on held-out games."
                    </dd>
                </div>
            </dl>

            <div class="chart-legend" aria-hidden="true">
                <span><i class="key key-train"></i>"train"</span>
                <span><i class="key key-val"></i>"validation"</span>
            </div>

            <figure class="chart">
                <svg viewBox="0 0 720 260" role="img" aria-label="Training and validation loss against optimizer step. Validation falls from 4.72 to 1.42 over 77,000 of 77,000 steps.">
                    <line class="grid" x1="42" x2="602" y1="184.7" y2="184.7"></line>
                    <line class="grid" x1="42" x2="602" y1="104.2" y2="104.2"></line>
                    <line class="grid" x1="42" x2="602" y1="23.7" y2="23.7"></line>
                    <line class="baseline" x1="42" x2="602" y1="232" y2="232"></line>
                    <text class="tick" x="34" y="188.7" text-anchor="end">"2.0"</text>
                    <text class="tick" x="34" y="108.2" text-anchor="end">"4.0"</text>
                    <text class="tick" x="34" y="27.7" text-anchor="end">"6.0"</text>
                    <text class="tick" x="42" y="250" text-anchor="middle">"0"</text>
                    <text class="tick" x="187.5" y="250" text-anchor="middle">"20k"</text>
                    <text class="tick" x="332.9" y="250" text-anchor="middle">"40k"</text>
                    <text class="tick" x="478.4" y="250" text-anchor="middle">"60k"</text>
                    <text class="tick" x="602" y="250" text-anchor="middle">"77k"</text>
                    <polyline class="series-val" points=VAL_LOSS_PTS></polyline>
                    <polyline class="series-train" points=TRAIN_LOSS_PTS></polyline>
                    <circle class="dot-val" cx="602" cy="208" r="4"></circle>
                    <circle class="dot-train" cx="602" cy="206.7" r="4"></circle>
                    <text class="end-label" x="612" y="217.8">"validation 1.42"</text>
                    <text class="end-label" x="612" y="204.8">"train 1.45"</text>
                </svg>
                <figcaption>
                    <strong>"Loss."</strong>
                    " How surprised the model is by the move that was played. One point per evaluation, every 500 steps. Train and validation track each other closely, which is what a single pass over a corpus this large should look like: the model has not seen enough of any position to memorize it."
                </figcaption>
            </figure>

            <figure class="chart">
                <svg viewBox="0 0 720 150" role="img" aria-label="Validation top-1 move accuracy against optimizer step. It rises from 19.2% to 53.4%.">
                    <line class="grid" x1="42" x2="704" y1="103.5" y2="103.5"></line>
                    <line class="grid" x1="42" x2="704" y1="55.8" y2="55.8"></line>
                    <line class="baseline" x1="42" x2="704" y1="122" y2="122"></line>
                    <text class="tick" x="34" y="107.5" text-anchor="end">"20%"</text>
                    <text class="tick" x="34" y="59.8" text-anchor="end">"40%"</text>
                    <text class="tick" x="42" y="140" text-anchor="middle">"0"</text>
                    <text class="tick" x="213.9" y="140" text-anchor="middle">"20k"</text>
                    <text class="tick" x="385.9" y="140" text-anchor="middle">"40k"</text>
                    <text class="tick" x="557.8" y="140" text-anchor="middle">"60k"</text>
                    <text class="tick" x="704" y="140" text-anchor="middle">"77k"</text>
                    <polyline class="series-val" points=TOP1_PTS></polyline>
                </svg>
                <figcaption>
                    <strong>"Move accuracy."</strong>
                    " How often the model's single best legal move is the one the human actually played, on held-out games. A perfect score is not the goal: strong players disagree with each other constantly, so most of the remaining gap is real choice rather than error."
                </figcaption>
            </figure>

            <figure class="chart">
                <svg viewBox="0 0 720 150" role="img" aria-label="Learning rate against optimizer step. It warms up to 3e-4, then decays on a cosine defined over the frozen 77,000-step horizon.">
                    <line class="grid" x1="42" x2="704" y1="87.1" y2="87.1"></line>
                    <line class="grid" x1="42" x2="704" y1="52.1" y2="52.1"></line>
                    <line class="grid" x1="42" x2="704" y1="17.2" y2="17.2"></line>
                    <line class="baseline" x1="42" x2="704" y1="122" y2="122"></line>
                    <text class="tick" x="34" y="91.1" text-anchor="end">"1e-4"</text>
                    <text class="tick" x="34" y="56.1" text-anchor="end">"2e-4"</text>
                    <text class="tick" x="34" y="21.2" text-anchor="end">"3e-4"</text>
                    <text class="tick" x="34" y="126" text-anchor="end">"0"</text>
                    <text class="tick" x="42" y="140" text-anchor="middle">"0"</text>
                    <text class="tick" x="213.9" y="140" text-anchor="middle">"20k"</text>
                    <text class="tick" x="385.9" y="140" text-anchor="middle">"40k"</text>
                    <text class="tick" x="557.8" y="140" text-anchor="middle">"60k"</text>
                    <text class="tick" x="704" y="140" text-anchor="middle">"77k"</text>
                    <polyline class="series-train" points=LR_PTS></polyline>
                </svg>
                <figcaption>
                    <strong>"Learning rate."</strong>
                    " The size of each weight update. It rises over the first 2% of the horizon, then follows a cosine decay defined over exactly the frozen step count, so late updates only make small adjustments. Changing the horizon would change the schedule, and therefore the model."
                </figcaption>
            </figure>
        </div>
    }
}
